apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    course: DevOps321
    Training: "siva kumar"

spec:
  #list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
